### PR TITLE
Reducing the time to commit proposals to 1 cycle

### PR DESCRIPTION
**Pull request by wiltchambers**
From discussions within the community, there's been an overwhelming consensus that the time a proposal will be committed should be lowered. Whether this would be temporary as things get more ironed out, I leave to the community. But this would allow for additional fixes to come in a faster rate in the meantime.

### CODE REVIEW

**Comment by jakeonfire** [comment]
it would be good to change the time to commit to be the same length. currently it is 142 epochs i think.

**Comment by mosesalan** [comment]
yes agree, please shorten time so implementation can act quickly, new project bound to have some bug, is silly to have to wait so long for a bug gix

**Comment by zimbabwean-inflation** [comment]
dev you're a fucking rookie coward piece of shit and you know it lol

**Comment by jakeonfire** [comment]
> it would be good to change the time to commit to be the same length. currently it is 142 epochs i think.

the commit time and vote time are both governed by `GOVERNANCE_PERIOD` so disregard this comment 😊

**Review by PatrickDehkordi — APPROVED** [review]
looks good

**Pull request merged**
